"""Wavegate v1 proto stubs — generated by grpcio-tools."""
# Pre-import google well-known types required by generated _pb2 files
import google.protobuf.timestamp_pb2  # noqa: F401
import google.protobuf.struct_pb2     # noqa: F401
import google.protobuf.empty_pb2      # noqa: F401

