# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2
from proto.wavegate.v1 import agent_pb2 as proto_dot_wavegate_dot_v1_dot_agent__pb2
from proto.wavegate.v1 import unified_message_pb2 as proto_dot_wavegate_dot_v1_dot_unified__message__pb2

GRPC_GENERATED_VERSION = '1.81.1'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in proto/wavegate/v1/agent_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class AgentStub:
    """── Agent Service ─────────────────────────────────────────────
    Implemented by the WW Agent Runtime. Wavegate calls this service
    to submit tasks, stream results, and manage sessions.

    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.RunTask = channel.unary_stream(
                '/wavegate.v1.Agent/RunTask',
                request_serializer=proto_dot_wavegate_dot_v1_dot_agent__pb2.RunTaskRequest.SerializeToString,
                response_deserializer=proto_dot_wavegate_dot_v1_dot_unified__message__pb2.AgentResponse.FromString,
                _registered_method=True)
        self.RunGoal = channel.unary_unary(
                '/wavegate.v1.Agent/RunGoal',
                request_serializer=proto_dot_wavegate_dot_v1_dot_agent__pb2.RunGoalRequest.SerializeToString,
                response_deserializer=proto_dot_wavegate_dot_v1_dot_agent__pb2.RunGoalResponse.FromString,
                _registered_method=True)
        self.WatchGoal = channel.unary_stream(
                '/wavegate.v1.Agent/WatchGoal',
                request_serializer=proto_dot_wavegate_dot_v1_dot_agent__pb2.WatchGoalRequest.SerializeToString,
                response_deserializer=proto_dot_wavegate_dot_v1_dot_unified__message__pb2.StatusUpdate.FromString,
                _registered_method=True)
        self.CancelGoal = channel.unary_unary(
                '/wavegate.v1.Agent/CancelGoal',
                request_serializer=proto_dot_wavegate_dot_v1_dot_agent__pb2.CancelGoalRequest.SerializeToString,
                response_deserializer=proto_dot_wavegate_dot_v1_dot_agent__pb2.CancelGoalResponse.FromString,
                _registered_method=True)
        self.SteerTask = channel.unary_unary(
                '/wavegate.v1.Agent/SteerTask',
                request_serializer=proto_dot_wavegate_dot_v1_dot_agent__pb2.SteerTaskRequest.SerializeToString,
                response_deserializer=proto_dot_wavegate_dot_v1_dot_agent__pb2.SteerTaskResponse.FromString,
                _registered_method=True)
        self.AbortTask = channel.unary_unary(
                '/wavegate.v1.Agent/AbortTask',
                request_serializer=proto_dot_wavegate_dot_v1_dot_agent__pb2.AbortTaskRequest.SerializeToString,
                response_deserializer=proto_dot_wavegate_dot_v1_dot_agent__pb2.AbortTaskResponse.FromString,
                _registered_method=True)
        self.AgentInfo = channel.unary_unary(
                '/wavegate.v1.Agent/AgentInfo',
                request_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
                response_deserializer=proto_dot_wavegate_dot_v1_dot_agent__pb2.AgentInfoResponse.FromString,
                _registered_method=True)


class AgentServicer:
    """── Agent Service ─────────────────────────────────────────────
    Implemented by the WW Agent Runtime. Wavegate calls this service
    to submit tasks, stream results, and manage sessions.

    """

    def RunTask(self, request, context):
        """Submit a task for synchronous execution. Blocks until the first response.
        For long-running tasks, subsequent responses arrive via the stream.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RunGoal(self, request, context):
        """Submit a goal for autonomous background execution (Goal Mode).
        Returns immediately with a task_id; progress arrives via StatusUpdate stream.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def WatchGoal(self, request, context):
        """Subscribe to status updates for a running goal.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CancelGoal(self, request, context):
        """Cancel a running goal.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SteerTask(self, request, context):
        """Steer an in-progress task: inject new context without interrupting.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def AbortTask(self, request, context):
        """Abort the currently running task for a session.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def AgentInfo(self, request, context):
        """Get agent health and capability info.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_AgentServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'RunTask': grpc.unary_stream_rpc_method_handler(
                    servicer.RunTask,
                    request_deserializer=proto_dot_wavegate_dot_v1_dot_agent__pb2.RunTaskRequest.FromString,
                    response_serializer=proto_dot_wavegate_dot_v1_dot_unified__message__pb2.AgentResponse.SerializeToString,
            ),
            'RunGoal': grpc.unary_unary_rpc_method_handler(
                    servicer.RunGoal,
                    request_deserializer=proto_dot_wavegate_dot_v1_dot_agent__pb2.RunGoalRequest.FromString,
                    response_serializer=proto_dot_wavegate_dot_v1_dot_agent__pb2.RunGoalResponse.SerializeToString,
            ),
            'WatchGoal': grpc.unary_stream_rpc_method_handler(
                    servicer.WatchGoal,
                    request_deserializer=proto_dot_wavegate_dot_v1_dot_agent__pb2.WatchGoalRequest.FromString,
                    response_serializer=proto_dot_wavegate_dot_v1_dot_unified__message__pb2.StatusUpdate.SerializeToString,
            ),
            'CancelGoal': grpc.unary_unary_rpc_method_handler(
                    servicer.CancelGoal,
                    request_deserializer=proto_dot_wavegate_dot_v1_dot_agent__pb2.CancelGoalRequest.FromString,
                    response_serializer=proto_dot_wavegate_dot_v1_dot_agent__pb2.CancelGoalResponse.SerializeToString,
            ),
            'SteerTask': grpc.unary_unary_rpc_method_handler(
                    servicer.SteerTask,
                    request_deserializer=proto_dot_wavegate_dot_v1_dot_agent__pb2.SteerTaskRequest.FromString,
                    response_serializer=proto_dot_wavegate_dot_v1_dot_agent__pb2.SteerTaskResponse.SerializeToString,
            ),
            'AbortTask': grpc.unary_unary_rpc_method_handler(
                    servicer.AbortTask,
                    request_deserializer=proto_dot_wavegate_dot_v1_dot_agent__pb2.AbortTaskRequest.FromString,
                    response_serializer=proto_dot_wavegate_dot_v1_dot_agent__pb2.AbortTaskResponse.SerializeToString,
            ),
            'AgentInfo': grpc.unary_unary_rpc_method_handler(
                    servicer.AgentInfo,
                    request_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                    response_serializer=proto_dot_wavegate_dot_v1_dot_agent__pb2.AgentInfoResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'wavegate.v1.Agent', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('wavegate.v1.Agent', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class Agent:
    """── Agent Service ─────────────────────────────────────────────
    Implemented by the WW Agent Runtime. Wavegate calls this service
    to submit tasks, stream results, and manage sessions.

    """

    @staticmethod
    def RunTask(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/wavegate.v1.Agent/RunTask',
            proto_dot_wavegate_dot_v1_dot_agent__pb2.RunTaskRequest.SerializeToString,
            proto_dot_wavegate_dot_v1_dot_unified__message__pb2.AgentResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def RunGoal(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/wavegate.v1.Agent/RunGoal',
            proto_dot_wavegate_dot_v1_dot_agent__pb2.RunGoalRequest.SerializeToString,
            proto_dot_wavegate_dot_v1_dot_agent__pb2.RunGoalResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def WatchGoal(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/wavegate.v1.Agent/WatchGoal',
            proto_dot_wavegate_dot_v1_dot_agent__pb2.WatchGoalRequest.SerializeToString,
            proto_dot_wavegate_dot_v1_dot_unified__message__pb2.StatusUpdate.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CancelGoal(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/wavegate.v1.Agent/CancelGoal',
            proto_dot_wavegate_dot_v1_dot_agent__pb2.CancelGoalRequest.SerializeToString,
            proto_dot_wavegate_dot_v1_dot_agent__pb2.CancelGoalResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SteerTask(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/wavegate.v1.Agent/SteerTask',
            proto_dot_wavegate_dot_v1_dot_agent__pb2.SteerTaskRequest.SerializeToString,
            proto_dot_wavegate_dot_v1_dot_agent__pb2.SteerTaskResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def AbortTask(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/wavegate.v1.Agent/AbortTask',
            proto_dot_wavegate_dot_v1_dot_agent__pb2.AbortTaskRequest.SerializeToString,
            proto_dot_wavegate_dot_v1_dot_agent__pb2.AbortTaskResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def AgentInfo(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/wavegate.v1.Agent/AgentInfo',
            google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            proto_dot_wavegate_dot_v1_dot_agent__pb2.AgentInfoResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
