# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: proto/wavegate/v1/gateway.proto
# Protobuf Python Version: 6.33.5
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    33,
    5,
    '',
    'proto/wavegate/v1/gateway.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1fproto/wavegate/v1/gateway.proto\x12\x0bwavegate.v1\x1a\'proto/wavegate/v1/unified_message.proto\x1a\x1bgoogle/protobuf/empty.proto\"P\n\rIngestRequest\x12,\n\x07message\x18\x01 \x01(\x0b\x32\x1b.wavegate.v1.UnifiedMessage\x12\x11\n\timmediate\x18\x02 \x01(\x08\"J\n\x0eIngestResponse\x12\x10\n\x08\x65vent_id\x18\x01 \x01(\t\x12\x0e\n\x06queued\x18\x02 \x01(\x08\x12\x16\n\x0equeue_position\x18\x03 \x01(\x05\"(\n\x11QueueStateRequest\x12\x13\n\x0bsession_key\x18\x01 \x01(\t\"p\n\x12QueueStateResponse\x12\x13\n\x0bsession_key\x18\x01 \x01(\t\x12\x17\n\x0fqueued_messages\x18\x02 \x01(\x05\x12\x16\n\x0e\x63urrent_status\x18\x03 \x01(\t\x12\x14\n\x0c\x63urrent_goal\x18\x04 \x01(\t\"7\n\x10InterruptRequest\x12\x13\n\x0bsession_key\x18\x01 \x01(\t\x12\x0e\n\x06reason\x18\x02 \x01(\t\"6\n\x11InterruptResponse\x12\x10\n\x08\x61\x63\x63\x65pted\x18\x01 \x01(\x08\x12\x0f\n\x07message\x18\x02 \x01(\t\"\x81\x01\n\x0eHealthResponse\x12\x0f\n\x07healthy\x18\x01 \x01(\x08\x12\x0f\n\x07version\x18\x02 \x01(\t\x12\x17\n\x0f\x61\x63tive_sessions\x18\x03 \x01(\x05\x12\x17\n\x0fqueued_messages\x18\x04 \x01(\x05\x12\x1b\n\x13\x63onnected_platforms\x18\x05 \x03(\t2\xf6\x02\n\x07Gateway\x12\x41\n\x06Ingest\x12\x1a.wavegate.v1.IngestRequest\x1a\x1b.wavegate.v1.IngestResponse\x12K\n\x0cStreamIngest\x12\x1b.wavegate.v1.UnifiedMessage\x1a\x1a.wavegate.v1.AgentResponse(\x01\x30\x01\x12P\n\rGetQueueState\x12\x1e.wavegate.v1.QueueStateRequest\x1a\x1f.wavegate.v1.QueueStateResponse\x12J\n\tInterrupt\x12\x1d.wavegate.v1.InterruptRequest\x1a\x1e.wavegate.v1.InterruptResponse\x12=\n\x06Health\x12\x16.google.protobuf.Empty\x1a\x1b.wavegate.v1.HealthResponseB>Z<github.com/clean-dust/worldwave/proto/wavegate/v1;wavegatev1b\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'proto.wavegate.v1.gateway_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z<github.com/clean-dust/worldwave/proto/wavegate/v1;wavegatev1'
  _globals['_INGESTREQUEST']._serialized_start=118
  _globals['_INGESTREQUEST']._serialized_end=198
  _globals['_INGESTRESPONSE']._serialized_start=200
  _globals['_INGESTRESPONSE']._serialized_end=274
  _globals['_QUEUESTATEREQUEST']._serialized_start=276
  _globals['_QUEUESTATEREQUEST']._serialized_end=316
  _globals['_QUEUESTATERESPONSE']._serialized_start=318
  _globals['_QUEUESTATERESPONSE']._serialized_end=430
  _globals['_INTERRUPTREQUEST']._serialized_start=432
  _globals['_INTERRUPTREQUEST']._serialized_end=487
  _globals['_INTERRUPTRESPONSE']._serialized_start=489
  _globals['_INTERRUPTRESPONSE']._serialized_end=543
  _globals['_HEALTHRESPONSE']._serialized_start=546
  _globals['_HEALTHRESPONSE']._serialized_end=675
  _globals['_GATEWAY']._serialized_start=678
  _globals['_GATEWAY']._serialized_end=1052
# @@protoc_insertion_point(module_scope)
