# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2
from proto.wavegate.v1 import gateway_pb2 as proto_dot_wavegate_dot_v1_dot_gateway__pb2
from proto.wavegate.v1 import unified_message_pb2 as proto_dot_wavegate_dot_v1_dot_unified__message__pb2

GRPC_GENERATED_VERSION = '1.81.1'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in proto/wavegate/v1/gateway_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class GatewayStub:
    """── Gateway Service ───────────────────────────────────────────
    Implemented by the Wavegate daemon. Platform adapters use this to
    inject normalized messages into the system.

    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Ingest = channel.unary_unary(
                '/wavegate.v1.Gateway/Ingest',
                request_serializer=proto_dot_wavegate_dot_v1_dot_gateway__pb2.IngestRequest.SerializeToString,
                response_deserializer=proto_dot_wavegate_dot_v1_dot_gateway__pb2.IngestResponse.FromString,
                _registered_method=True)
        self.StreamIngest = channel.stream_stream(
                '/wavegate.v1.Gateway/StreamIngest',
                request_serializer=proto_dot_wavegate_dot_v1_dot_unified__message__pb2.UnifiedMessage.SerializeToString,
                response_deserializer=proto_dot_wavegate_dot_v1_dot_unified__message__pb2.AgentResponse.FromString,
                _registered_method=True)
        self.GetQueueState = channel.unary_unary(
                '/wavegate.v1.Gateway/GetQueueState',
                request_serializer=proto_dot_wavegate_dot_v1_dot_gateway__pb2.QueueStateRequest.SerializeToString,
                response_deserializer=proto_dot_wavegate_dot_v1_dot_gateway__pb2.QueueStateResponse.FromString,
                _registered_method=True)
        self.Interrupt = channel.unary_unary(
                '/wavegate.v1.Gateway/Interrupt',
                request_serializer=proto_dot_wavegate_dot_v1_dot_gateway__pb2.InterruptRequest.SerializeToString,
                response_deserializer=proto_dot_wavegate_dot_v1_dot_gateway__pb2.InterruptResponse.FromString,
                _registered_method=True)
        self.Health = channel.unary_unary(
                '/wavegate.v1.Gateway/Health',
                request_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
                response_deserializer=proto_dot_wavegate_dot_v1_dot_gateway__pb2.HealthResponse.FromString,
                _registered_method=True)


class GatewayServicer:
    """── Gateway Service ───────────────────────────────────────────
    Implemented by the Wavegate daemon. Platform adapters use this to
    inject normalized messages into the system.

    """

    def Ingest(self, request, context):
        """Push a single message into the system. Returns immediately with an ACK.
        The message is queued and processed asynchronously by the Agent runtime.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StreamIngest(self, request_iterator, context):
        """Open a bidirectional stream for a platform adapter.
        The adapter sends UnifiedMessages; the gateway streams back AgentResponses.
        Used for platforms that need real-time streaming replies (Telegram, Discord).
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetQueueState(self, request, context):
        """Query the current queue state for a session.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Interrupt(self, request, context):
        """Send an interrupt signal to abort the current task for a session.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Health(self, request, context):
        """Health check.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_GatewayServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Ingest': grpc.unary_unary_rpc_method_handler(
                    servicer.Ingest,
                    request_deserializer=proto_dot_wavegate_dot_v1_dot_gateway__pb2.IngestRequest.FromString,
                    response_serializer=proto_dot_wavegate_dot_v1_dot_gateway__pb2.IngestResponse.SerializeToString,
            ),
            'StreamIngest': grpc.stream_stream_rpc_method_handler(
                    servicer.StreamIngest,
                    request_deserializer=proto_dot_wavegate_dot_v1_dot_unified__message__pb2.UnifiedMessage.FromString,
                    response_serializer=proto_dot_wavegate_dot_v1_dot_unified__message__pb2.AgentResponse.SerializeToString,
            ),
            'GetQueueState': grpc.unary_unary_rpc_method_handler(
                    servicer.GetQueueState,
                    request_deserializer=proto_dot_wavegate_dot_v1_dot_gateway__pb2.QueueStateRequest.FromString,
                    response_serializer=proto_dot_wavegate_dot_v1_dot_gateway__pb2.QueueStateResponse.SerializeToString,
            ),
            'Interrupt': grpc.unary_unary_rpc_method_handler(
                    servicer.Interrupt,
                    request_deserializer=proto_dot_wavegate_dot_v1_dot_gateway__pb2.InterruptRequest.FromString,
                    response_serializer=proto_dot_wavegate_dot_v1_dot_gateway__pb2.InterruptResponse.SerializeToString,
            ),
            'Health': grpc.unary_unary_rpc_method_handler(
                    servicer.Health,
                    request_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                    response_serializer=proto_dot_wavegate_dot_v1_dot_gateway__pb2.HealthResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'wavegate.v1.Gateway', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('wavegate.v1.Gateway', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class Gateway:
    """── Gateway Service ───────────────────────────────────────────
    Implemented by the Wavegate daemon. Platform adapters use this to
    inject normalized messages into the system.

    """

    @staticmethod
    def Ingest(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/wavegate.v1.Gateway/Ingest',
            proto_dot_wavegate_dot_v1_dot_gateway__pb2.IngestRequest.SerializeToString,
            proto_dot_wavegate_dot_v1_dot_gateway__pb2.IngestResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def StreamIngest(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_stream(
            request_iterator,
            target,
            '/wavegate.v1.Gateway/StreamIngest',
            proto_dot_wavegate_dot_v1_dot_unified__message__pb2.UnifiedMessage.SerializeToString,
            proto_dot_wavegate_dot_v1_dot_unified__message__pb2.AgentResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetQueueState(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/wavegate.v1.Gateway/GetQueueState',
            proto_dot_wavegate_dot_v1_dot_gateway__pb2.QueueStateRequest.SerializeToString,
            proto_dot_wavegate_dot_v1_dot_gateway__pb2.QueueStateResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Interrupt(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/wavegate.v1.Gateway/Interrupt',
            proto_dot_wavegate_dot_v1_dot_gateway__pb2.InterruptRequest.SerializeToString,
            proto_dot_wavegate_dot_v1_dot_gateway__pb2.InterruptResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Health(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/wavegate.v1.Gateway/Health',
            google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            proto_dot_wavegate_dot_v1_dot_gateway__pb2.HealthResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
